version: '3.8'

services:
  prometheus-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.backnd-api.cloud`)"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.services.prometheus.loadbalancer.server.port=8000"
